# Generated by Django 4.2.4 on 2024-02-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='link_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
