# Generated by Django 4.2.4 on 2024-02-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mymodel_available_mymodel_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Product',
        ),
    ]
