# Generated by Django 4.2.4 on 2024-02-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_mymodel_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('points', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(blank=True, to='api.product')),
            ],
        ),
    ]
